version: "3"

services:
  mongo:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=diego
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
      - ./db/home/mongodb:/home/mongodb
    expose:
      - '27017'

  api:
    build: ./web
    depends_on:
      - mongo
    environment:
      - DB_NAME=mongo
    ports:
      - '8080:8080'